// <auto-generated />
using System;
using Docker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Docker.Data.Migrations
{
    [DbContext(typeof(DockerDbContext))]
    partial class DockerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Docker.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 10, 1, 15, 10, 28, 969, DateTimeKind.Unspecified).AddTicks(8260), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "First product",
                            Name = "Product 1",
                            Price = 10m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2020, 10, 1, 15, 10, 28, 971, DateTimeKind.Unspecified).AddTicks(3197), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 10, 1, 15, 10, 28, 971, DateTimeKind.Unspecified).AddTicks(3519), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Second product",
                            Name = "Product 2",
                            Price = 15m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2020, 10, 1, 15, 10, 28, 971, DateTimeKind.Unspecified).AddTicks(3529), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 10, 1, 15, 10, 28, 971, DateTimeKind.Unspecified).AddTicks(3532), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Third product",
                            Name = "Product 3",
                            Price = 20m,
                            Stock = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2020, 10, 1, 15, 10, 28, 971, DateTimeKind.Unspecified).AddTicks(3536), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
