apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: docker-poc
build:
  artifacts:
    - image: christiaanderidder/docker-poc-web
      context: ../
      docker: 
        dockerfile: src/Web/Docker.Web/Dockerfile
    - image: christiaanderidder/docker-poc-api
      context: ../
      docker: 
        dockerfile: src/Web/Docker.Api/Dockerfile
    - image: christiaanderidder/docker-poc-oauth
      context: ../
      docker: 
        dockerfile: src/Web/Docker.OAuth/Dockerfile
    - image: christiaanderidder/docker-poc-worker
      context: ../
      docker: 
        dockerfile: src/Worker/Docker.Worker/Dockerfile
deploy:
  kubectl:
    manifests:
    - ..\k8s\*.yaml
